import { useEffect, useState } from 'react';
import { getLeaders } from '../api/playersApi';
import type { PlayerStatsResponse } from '../types';
import Loading from '../components/Loading';
import ErrorMessage from '../components/ErrorMessage';
import PlayerDetailsModal from '../components/PlayerDetailsModal';
import TeamCrest from '../components/TeamCrest';

type StatTab = 'goals' | 'assists' | 'redCards';

const TABS: { key: StatTab; label: string; statLabel: string; testId: string }[] = [
  { key: 'goals', label: 'Top Scorers', statLabel: 'Goals', testId: 'stats-tab-goals' },
  { key: 'assists', label: 'Top Assists', statLabel: 'Assists', testId: 'stats-tab-assists' },
  { key: 'redCards', label: 'Red Cards', statLabel: 'Red Cards', testId: 'stats-tab-redCards' },
];

function statValue(p: PlayerStatsResponse, tab: StatTab): number {
  if (tab === 'goals') return p.goals;
  if (tab === 'assists') return p.assists;
  return p.redCards;
}

function LeadersTable({ tab }: { tab: StatTab }) {
  const [players, setPlayers] = useState<PlayerStatsResponse[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [selectedPlayer, setSelectedPlayer] = useState<PlayerStatsResponse | null>(null);

  useEffect(() => {
    setLoading(true);
    setError('');
    getLeaders(tab, 20)
      .then((res) => setPlayers(res.data))
      .catch(() => setError('Failed to load stats.'))
      .finally(() => setLoading(false));
  }, [tab]);

  if (loading) return <Loading />;
  if (error) return <ErrorMessage message={error} />;

  const config = TABS.find((t) => t.key === tab)!;

  return (
    <div data-testid={config.testId}>
      {players.length === 0 ? (
        <p className="muted">The leaderboard is empty — stats appear once matches are simulated.</p>
      ) : (
        <table className="data-table">
          <thead>
            <tr>
              <th>Rank</th>
              <th>Player</th>
              <th>Team</th>
              <th>Position</th>
              <th>{config.statLabel}</th>
              <th>Rating</th>
            </tr>
          </thead>
          <tbody>
            {players.map((p, i) => (
              <tr
                key={p.playerId}
                className="clickable-row"
                data-testid={`${config.testId}-row-${p.playerId}`}
                onClick={() => setSelectedPlayer(p)}
              >
                <td>{i + 1}</td>
                <td>{p.fullName}</td>
                <td>
                  <span style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
                    <TeamCrest name={p.teamName} size="sm" />
                    {p.teamName}
                  </span>
                </td>
                <td><span className={`pos-badge ${p.position.toLowerCase()}`}>{p.position}</span></td>
                <td><strong>{statValue(p, tab)}</strong></td>
                <td>{p.rating}</td>
              </tr>
            ))}
          </tbody>
        </table>
      )}

      {selectedPlayer && (
        <PlayerDetailsModal
          player={selectedPlayer}
          teamName={selectedPlayer.teamName}
          onClose={() => setSelectedPlayer(null)}
        />
      )}
    </div>
  );
}

export default function StatsPage() {
  const [activeTab, setActiveTab] = useState<StatTab>('goals');

  return (
    <div className="page page-stats">
      <h1>Player Stats</h1>
      <p className="muted">
        Stats are generated by match simulation (goals, assists, red cards) — they are not imported real-world statistics.
      </p>

      <div className="tabs" data-testid="stats-tabs">
        {TABS.map((t) => (
          <button
            key={t.key}
            className={`tab-button ${activeTab === t.key ? 'active' : ''}`}
            data-testid={`stats-tab-button-${t.key}`}
            onClick={() => setActiveTab(t.key)}
          >
            {t.label}
          </button>
        ))}
      </div>

      <h2>{TABS.find((t) => t.key === activeTab)!.label}</h2>
      <LeadersTable tab={activeTab} />
    </div>
  );
}
